#--------------------------------
#       General Params
#--------------------------------
seed: [True, 1337]
train: True
model_id: 'early_testing'
demo: True
torch_home: '~/.cache/torch/'

#--------------------------------
#       Training Params
#--------------------------------

batch_size: 8
num_epochs: 5
accelerator: 'gpu' 
gpu_config: [True, [0]]
valid_rate: 1

#--------------------------------
#       All paths
#--------------------------------

paths: &id001
  #path_root: '/home/mblgh6/Documents/diffractive_optical_model'
  #path_root: '/home/marshall/Documents/research/'
  #path_root: '/Users/marshalllindsay/research/diffractive_optical_model/'
  path_root: 
  path_bench: 'optics_bench'
  path_sim: 'diffractive_optical_model'
  
  path_data: 'data/'
  path_train: 'train/'
  path_valid: 'valid/'
  path_model: 'my_models/'
  path_results: 'results/'
  
  path_checkpoint: 'my_models/'
  path_checkpoint_don: 'my_models/'


#--------------------------------
#       DOM params
#--------------------------------
wavelength: &wavelength 520.e-6

planes:
  0: &idpl00
    name: 'input_plane'
    center: [0,0,0]
    size: [15.36, 8.64]
    normal: [0,0,1]
    Nx: &input_x 1920
    Ny: &input_y 1080
  1: &idpl01
    name: 'lens_plane'
    center: [0,0,762]
    size: [15.36, 8.64]
    normal: [0,0,1]
    Nx: 1920
    Ny: 1080
  2: &idpl02
    name: 'output_plane'
    center: [0,0, 1219.2]
    size: [9.6768, 5.4432]
    normal: [0,0,1]
    Nx: 1920
    Ny: 1080

modulators:
  0: &idm00
    gradients : 'none'
    amplitude_init : 'uniform'
    amplitude_value: 1.0
    pinhole_size: 'none'
    phase_init : 'uniform'
    phase_value: 0.0
    focal_length: 'none'
    wavelength: *wavelength 
  1: &idm01
    gradients : 'none'
    amplitude_init : 'uniform'
    amplitude_value : 1.0
    pinhole_size: 0.0
    phase_init : 'lens_phase'
    phase_value : 0.0
    focal_length: 285.75
    wavelength: *wavelength

propagator: &idprop
  wavelength: *wavelength
  fft_type: 'auto'
  prop_type: 'rsc'
  padded : True

diffraction_blocks:
  0:
    input_plane : *idpl00
    output_plane : *idpl01
    modulator_params : *idm00
    propagator_params : *idprop
  1:
    input_plane : *idpl01
    output_plane : *idpl02
    modulator_params : *idm01
    propagator_params : *idprop

dom_training:
  optimizer: 'ADAM'
  learning_rate: 3.e-1
  transfer_learn: False
  load_checkpoint: False
  objective_function: 'mse'

#--------------------------------
#       Datamodule Params
#--------------------------------
which: 'MNIST'
n_cpus: 2
resize_row: 1080
resize_col: 1080
Nxp : *input_x
Nyp : *input_y

wavefront_transform:
    phase_initialization_strategy: 0
