#--------------------------------
#       General Params
#--------------------------------
seed: [True, 1337]
train: True
model_id: 'early_testing'
demo: True
torch_home: '~/.cache/torch/'

#--------------------------------
#       Training Params
#--------------------------------

batch_size: 2
num_epochs: 5
accelerator: 'gpu' 
gpu_config: [True, [0]]
valid_rate: 1

#--------------------------------
#       All paths
#--------------------------------

paths: &id001
  #path_root: '/home/mblgh6/Documents/diffractive_optical_model'
  #path_root: '/home/marshall/Documents/research/'
  #path_root: '/Users/marshalllindsay/research/diffractive_optical_model/'
  path_root: 
  path_bench: 'optics_bench'
  path_sim: 'diffractive_optical_model'
  
  path_data: 'data/'
  path_train: 'train/'
  path_valid: 'valid/'
  path_model: 'my_models/'
  path_results: 'results/'
  
  path_checkpoint: 'my_models/'
  path_checkpoint_don: 'my_models/'

#--------------------------------
#       Classifier Params
#--------------------------------
#Classifier
num_classes: 10
freeze_backbone: False
num_layers_classifier: 1
name_classifier: 'resnet18'
optimizer_classifier: 'ADAM'
learning_rate_classifier: 0.001
transfer_learn_classifier: True
load_checkpoint_classifier: False
objective_function_classifier: 'cross_entropy'

#Cooperative
load_checkpoint_cooperative: False

#--------------------------------
#       DON Params
#--------------------------------
# Model / learning
optimizer_don: 'ADAM'
learning_rate_don: 3.e-1
transfer_learn_don: False
load_checkpoint_don: False
objective_function_don: 'mse'

# Data
Nxp: 1920
Nyp: 1080
Lxp: 15.36e-3
Lyp: 8.96e-3
  #Lyp: 8.96e-3

#--------------------------------
#       CITL Params
#--------------------------------
load_checkpoint_citl: False
learning_rate_citl: 3.e-1

#--------------------------------
#       Datamodule Params
#--------------------------------
#flat_calibration, MNIST
which: 'MNIST'
n_cpus: 2
resize_row: 1080
resize_col: 1080

wavefront_transform:
    phase_initialization_strategy: 0

# Start of new parameters
planes:
  0: &idpl00
    name: 'plane0'
    center: [0,0,0]
    size: [15.36e+3, 8.96e+3]
    normal: [0,0,1]
    Nx: 1920
    Ny: 1080
  1: &idpl01
    name: 'plane1'
    center: [0,0,10.e+4]
    size: [15.36e+3, 8.96e+3]
    normal: [0,0,1]
    Nx: 1920
    Ny: 1080
  2: &idpl02
    name: 'plane2'
    center: [0,0,20.e+4]
    size: [15.36e+3, 8.96e+3]
    normal: [0,0,1]
    Nx: 1920
    Ny: 1080

modulators:
  0: &idm00
    amplitude_init : 'uniform'
    phase_init : 'uniform'
    gradients : 'none'
    phase_pattern : None
    amplitude_pattern : None
    kwargs:
  1: &idm01
    amplitude_init : 'uniform'
    phase_init : 'custom'
    gradients : 'phase_only'
    phase_pattern : 'lens'
    amplitude_pattern : None
    kwargs:
      focal_length: 5.e+4
      wavelength: 1.55

propagator: &idprop
  prop_type: 
  wavelength: 1.55

diffraction_blocks:
  0:
    input_plane : *idpl00
    output_plane : *idpl01
    modulator_params : *idm00
    propagator_params : *idprop
  1:
    input_plane : *idpl01
    output_plane : *idpl02
    modulator_params : *idm01
    propagator_params : *idprop


don:
  optimizer: 'ADAM'
  learning_rate: 3.e-1
  transfer_learn: False
  load_checkpoint: False
  objective_function: 'mse'
